//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiaPortalOpennessDemo.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideAssemblySelection
        {
            get
            {
                return ((bool)(this["HideAssemblySelection"]));
            }
            set
            {
                this["HideAssemblySelection"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15.0")]
        public string EngineeringVersion
        {
            get
            {
                return ((string)(this["EngineeringVersion"]));
            }
            set
            {
                this["EngineeringVersion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15.0.0.0")]
        public string AssemblyVersion
        {
            get
            {
                return ((string)(this["AssemblyVersion"]));
            }
            set
            {
                this["AssemblyVersion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp")]
        public string DefaultExportPath
        {
            get
            {
                return ((string)(this["DefaultExportPath"]));
            }
            set
            {
                this["DefaultExportPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\TiaPortalOpenness")]
        public string MainFolderPath
        {
            get
            {
                return ((string)(this["MainFolderPath"]));
            }
            set
            {
                this["MainFolderPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultSchnittstellePath
        {
            get
            {
                return ((string)(this["DefaultSchnittstellePath"]));
            }
            set
            {
                this["DefaultSchnittstellePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultPlcDBPath
        {
            get
            {
                return ((string)(this["DefaultPlcDBPath"]));
            }
            set
            {
                this["DefaultPlcDBPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultSequencePath
        {
            get
            {
                return ((string)(this["DefaultSequencePath"]));
            }
            set
            {
                this["DefaultSequencePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultNetworkListPath
        {
            get
            {
                return ((string)(this["DefaultNetworkListPath"]));
            }
            set
            {
                this["DefaultNetworkListPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultEPlanPath
        {
            get
            {
                return ((string)(this["DefaultEPlanPath"]));
            }
            set
            {
                this["DefaultEPlanPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserInterfaceEnabled
        {
            get
            {
                return ((bool)(this["UserInterfaceEnabled"]));
            }
            set
            {
                this["UserInterfaceEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportWithDefaults
        {
            get
            {
                return ((bool)(this["ExportWithDefaults"]));
            }
            set
            {
                this["ExportWithDefaults"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportReadOnly
        {
            get
            {
                return ((bool)(this["ExportReadOnly"]));
            }
            set
            {
                this["ExportReadOnly"] = value;
            }
        }
    }
}
